apiVersion: v1
kind: Service
metadata:
  labels:
    app: bets
    stack: echo
    interface: rest
    language: golang
  name: bets
  annotations:
    kong.ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: bets