apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bets-api
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/override: do-not-preserve-host
    konghq.com/plugins: oidc-bets,rl-by-ip
spec:
  rules:
    - http:
        paths:
          - path: /api/bets
            backend:
              serviceName: bets
              servicePort: 9999